/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jonesx_videoplayer_VideoPlayer */

#ifndef _Included_jonesx_videoplayer_VideoPlayer
#define _Included_jonesx_videoplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL Java_com_sherlock_ffmpegdemo_MainActivity_play
  (JNIEnv *, jclass clazz, jstring filePath, jobject);

#ifdef __cplusplus
}
#endif
#endif
